//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE.SIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLedger
    {
        public long ProductLedgerID { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string InvoiceNo { get; set; }
        public string Description { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public int Balance { get; set; }
        public string UserName { get; set; }
        public long ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
