//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE.SIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SalesDetails = new HashSet<SalesDetail>();
            this.SalesReturns = new HashSet<SalesReturn>();
        }
    
        public long SalesID { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string InvoiceNo { get; set; }
        public string Remarks { get; set; }
        public double Discount { get; set; }
        public long CustomerID { get; set; }
        public long SalesAgentID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesAgent SalesAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
    }
}
